In [1]:
import numpy as np

In [2]:
flowers = np.array([[50,60,25],[10,13,5],[40,70,52]])
flowers

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [4]:
price_per_item = np.array([20,30,15])
price_per_item

array([20, 30, 15])

In [6]:
total_sales = np.dot(flowers, price_per_item)
total_sales

array([3175,  665, 3680])

In [7]:
total_sales = flowers.dot(price_per_item)
total_sales

array([3175,  665, 3680])