In [131]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers 
import warnings
warnings.filterwarnings("ignore")

In [132]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [133]:

one_hot("amazing restaurant",30)

[5, 3]

In [134]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[4, 15], [5, 3], [12, 6], [18, 16, 14], [8, 12, 12], [24, 15], [8, 12, 4], [17, 28], [17, 5], [7, 15]]


In [135]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 4 15  0  0]
 [ 5  3  0  0]
 [12  6  0  0]
 [18 16 14  0]
 [ 8 12 12  0]
 [24 15  0  0]
 [ 8 12  4  0]
 [17 28  0  0]
 [17  5  0  0]
 [ 7 15  0  0]]


In [136]:
embeded_vector_size = 5

model = Sequential([
    layers.Embedding(input_dim=vocab_size, 
                    output_dim=embeded_vector_size, 
                    input_length=max_length,
                    name="embedding"),
    layers.Flatten(),
    layers.Dense(1, activation='sigmoid')
])

In [137]:
X = padded_reviews
y = sentiment

In [138]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_13 (Flatten)            │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [139]:
model.fit(X, y, epochs=50, verbose=0)

In [140]:
loss, accuracy = model.evaluate(X, y)
accuracy


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step - accuracy: 1.0000 - loss: 0.6324


1.0

In [141]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [142]:
weights[3]

array([ 0.01870981,  0.03320749, -0.00208204, -0.04420957, -0.04071945],
      dtype=float32)

In [143]:
weights[16]

array([ 0.0886686 ,  0.09107835, -0.08674555, -0.03441208, -0.05959063],
      dtype=float32)